#!/bin/sh
mkdir -p /lib/firmware/brcm/
OTP_CHIP_ID=`cat /sys/module/brcmfmac/parameters/otp_chip_id`
OTP_NVRAM_ID=`cat /sys/module/brcmfmac/parameters/otp_nvram_id`
KRISTOFF=`ls -la /sys/bus/pci/devices|fgrep "00:03.0"`

if [ $? -ne 0 ]; then
    CHIP="elsa"
else
    CHIP="kristoff"
fi

ln -s /mnt/usr/share/firmware/wifi/${OTP_CHIP_ID}/${CHIP}.trx /lib/firmware/brcm/brcmfmac4355-pcie.bin
ln -s /mnt/usr/share/firmware/wifi/${OTP_CHIP_ID}/${CHIP}.clmb /lib/firmware/brcm/brcmfmac4355-pcie.clm_blob
ln -s /mnt/usr/share/firmware/wifi/${OTP_CHIP_ID}/P-${CHIP}_${OTP_NVRAM_ID}.txt /lib/firmware/brcm/brcmfmac4355-pcie.hx,h9p.txt

/usr/bin/syscfg /dev/nvme0n3 WMac x:6 > /sys/module/brcmfmac/parameters/nvram_mac_addr
for RETRY in `seq 1 3`; do
    echo 1 > /sys/bus/pci/devices/0000:02:00.0/remove
    sleep 1
    echo 1 > /sys/bus/pci/devices/0000:00:02.0/dev_rescan
    echo 1 > /sys/bus/pci/devices/0000:00:03.0/dev_rescan
    for DELAY in `seq 1 6`; do
        if [ -e /sys/class/net/wlan0 ]; then
            ifconfig wlan0 up
            exit 0
        fi
        sleep 1
    done
done

echo WLAN start up failed.
